[package]
name = "ghost-cell"
version = "0.2.3"
authors = ["Matthieu M. <matthieum.147192@gmail.com>"]
edition = "2021"
description = "Compile-time zero-cost borrow-checking of aliased references"
repository = "https://github.com/matthieu-m/ghost-cell"
license = "MIT OR Ap